export default [
  {
    category: "Dev",
    color: "cyan",
    items: {
      Github: "https://github.com",
      AWS: "https://aws.amazon.com",
      "Dev.to": "https://dev.to",
      Firebase: "https://console.firebase.google.com/u/0",
      Hackaday: "https://hackaday.com",
      "CNX Software": "https://www.cnx-software.com",
    },
  },
  {
    category: "Work",
    color: "red",
    items: {
      Altium: "https://kaertech.365.altium.com",
      Odoo: "https://erp.kaertech.com/web?#home",
      Sharepoint: "https://kaertech-my.sharepoint.com",
      Chirpstack: "https://eng-chirpstack.kaertech.com",
      Grafana: "https://eng-grafana.kaertech.com",
      InfluxDB: "https://eng-influxdb.kaertech.com",
    },
  },
  {
    category: "Home Lab",
    color: "green",
    items: {
      OPNsense: "https://opnsense.will-tm.io",
      Proxmox: "https://proxmox.will-tm.io",
      Grafana: "https://grafana.will-tm.io",
      TrueNAS: "https://truenas.will-tm.io",
      "Uptime Kuma": "https://kuma.will-tm.io",
      "Unifi Controller": "https://unifi-controller.will-tm.io",
      "Uptime Kuma": "https://kuma.will-tm.io",
      Britwarden: "https://vault.will-tm.io",
      Homebridge: "https://homebridge.will-tm.io",
    },
  },
  {
    category: "Misc",
    color: "purple",
    items: {
      YouTube: "https://www.youtube.com/",
      Reddit: "https://www.reddit.com/",
      Gmail: "https://mail.google.com/",
      Reddit: "https://www.reddit.com/",
      "1337X": "https://1337x.to/",
      "BV live": "https://live.beyondvisuals.hk",
      Octoprint: "https://octoprint.will-tm.io",
      Plex: "https://plex.will-tm.io",
    },
  },
];
